# ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
# |▌▐|▌                        ▐|▌▐|
# |▌▐|▌ ●    MultiOption       ▐|▌▐|
# |▌▐|▌ ● By jonagamerpro1234  ▐|▌▐| 
# |▌▐|▌ ●   Vesion 4.0.0       ▐|▌▐|
# |▌▐|▌                        ▐|▌▐|
# ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
#
# ● MultiOptions is a simple plugin that will help you on your server and facilitates the customization and progress of your server with the multiple options that it brings
#
# ● GitHub: https://github.com/jonagamerpro1234/MultiOptions
# ● Spigot: https://www.spigotmc.org/resources/53655/
# ● Discord: https://discord.gg/c5GhQDQCK5
# ● Bstast: https://bstats.org/plugin/bukkit/MultiOptions/4583
# ● Wiki: !comming soon!
#
Settings:
  
  #
  Config-Version: 1
  
  #
  Debug: false
  
  #
  Prefix: '&e[&bMy Server&e]&7'
  
  #
  Use-Default-Prefix: true
  
  #
  Update: true
  
  Modules:
    
    Fly: true
    
    Lobby: true
    
    Warps: true
    
    Vanish: true
  
    Gamemode: true
#
#
Vanish:
  
  #
  Enabled: true
  
  #
  Silent-Join: false
  
  #
  Show-Potion-Effect: true
#
#
Spawn:
  
  #
  Enabled: true
  
  #
  Use-Blindness: false
  
  #
  Cooldown: 5
  
  #
  Requiered-Permission: false
#
#  
Warps:
  
  #
  Enabled: true
  
  #
  Cooldown: 5
  
  #
  Requiered-Permission: false
#
#  
Teleport:
  
  #
  Enabled: true
  
  #
  Cooldown: 10
  
  #
  Show-Menu: false
  
  #
  Intective-Tp: false
#
#
GameMode:
  
  #
  Enabled-Custom-GameMode: true
  
  #
  Survival:
    
    #
    Enabled: true
    
    #
    Message: ''

  #
  Creative:
    
    #
    Enabled: true
    
    #
    Message: ''
  
  #  
  Adventure:
    
    #
    Enabled: true
    
    #
    Message: ''
  
  #  
  Spectator:
    
    #
    Enabled: true
    
    #
    Message: '' 
#
#    
Fly:
  
  #
  Enabled: true
  
  #
  Speed: 1.0
  

#
# This is the end of the configuration ... [-_-] more things coming soon
# 
# | Config File
# | Version 4.0.0
#