# ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
# |▌▐|▌                        ▌|▌▐|
# |▌▐|▌ ●    MultiOption       ▌|▌▐|
# |▌▐|▌ ● By jonagamerpro1234  ▌|▌▐| 
# |▌▐|▌ ●   Vesion 4.0.0       ▌|▌▐|
# |▌▐|▌                        ▌|▌▐|
# ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
#
#
# | Settings |
#
Settings:
  Debug: false
  Prefix: '&e[&bMy Server&e]&7'
  Use-Default-Prefix: true
  Update: true
  ClearChat:
    AutoClear: 
      Enabled: true
      Tick: 24000
#
# | Join and Quit |
#
Join:
  Enabled: true
  Text: '&3[&a+&3] &e<displayname> &7entered the server'
  Use-Permission: false
  Permission: 'my.server.join'
  Type: normal
  HoverEvent:
    Text:
      -
    Type: text
  ClickEvent:
    Action: 'give <name> minecraft:diamonds 1'
    Type: cmd
Quit:
  Enabled: true
  Text: '&3[&c-&3] &e<displayname> &7left the server'
  Use-Permission: false
  Permission: 'my.server.join'
  Type: normal
  HoverEvent:
    Text: ''
    Type: text
  ClickEvent:
    Action: 'give <name> minecraft:diamonds 1'
    Type: cmd
#
# | Welcome or Motd |
#
Welcome:
  Enabled: true
  Text:
    - '&b&m=========================================&r'
    - '<0>'
    - '&e> &7Welcome To The Server &b<name>'
    - '<0>'
    - '&e> &cShop: shop-example.com'
    - '&e> &7Use &b/skin to put on a skin'
    - '<0>'
    - '&b&m=========================================&r'
#
# | Sounds |
# 
#
Sounds:
  Enabled: true
#
# This is the end of the configuration ... [-_-] more things coming soon
# 
# | Config File
# | Version 4.0.0
#